In [98]:
import pandas as pd
import numpy as np
import re

In [99]:
data = pd.read_csv('clean_this_only_no_time_wasting.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_10364\703663496.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('clean_this_only_no_time_wasting.csv')

In [100]:
#rename the columns Unnamed: 7, Unnamed: 8 to 'new_col1', 'new_col2'
data.rename(columns={'Unnamed: 7':'new_col1', 'Unnamed: 8':'new_col2', 'Unnamed: 2' : 'Preferential_Rate(Agreement rate)_1'}, inplace=True)

In [101]:
#add empty column named 'guard_col'
data['guard_col1'] = np.nan
data['guard_col2'] = np.nan

In [102]:
#get me the rows where Unnamed: 7, Unnamed: 8 are not null as dataframe
data[data['new_col1'].notnull() & data['new_col2'].notnull()]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
26972,"4412.5919 ----其他,中间至少有一层是其他 6∆0",0,"智CL,新西兰NZ,瑞CH,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
26978,"4412.5920 ---其他,中间至少含有一层木碎 6∆0",0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
26982,4412.5990 ---其他 4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
26988,4412.9100 --至少有一表层是热带木 6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
26994,"4412.9200 --其他,至少有一表层是非针叶木 6∆0",0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
27001,4412.9920 ---中间至少有一层是本章本国注 6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
27005,"R4412.9930 ---其他,中间至少有一层是其他 6∆0",0,"智CL,新西兰NZ,瑞CH,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
27011,"4412.9940 ---其他,中间至少含有一层木碎 6∆0",0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN
27015,4412.9990 ---其他 4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN,NaN

In [103]:
# extract where HScode contains value like 4412.5919 and the next 5 lines. Use regex. To ensure no missing data points. 
# Convert HS_code column to string
# data['HS_code'] = data['HS_code'].astype(str)

# # Find all indices where HS_code contains '4412.5919' using regex
# pattern = r'4412\.9100'
# matching_indices = data[data['HS_code'].str.contains(pattern, regex=True)].index.tolist()

# # For each matching index, get the next 5 rows (including the matching row)
# result_indices = []
# for idx in matching_indices:
#     end_idx = min(idx + 6, len(data))  # Ensure we don't go beyond DataFrame length
#     result_indices.extend(range(idx, end_idx))

# # Remove duplicates and sort the indices
# result_indices = sorted(list(set(result_indices)))

# # Extract the resulting rows
# result_df = data.iloc[result_indices].reset_index(drop=True)

# # Display the result
# result_df

In [104]:
# # Convert HS_code column to string
# data['HS_code'] = data['HS_code'].astype(str)

# # Function to extract the last numeric value (including values like 6∆0)
# def extract_last_value(value):
#     # Split the row into segments based on whitespace
#     segments = value.strip().split()
#     # Get the last segment
#     last_segment = segments[-1]
#     # Check if the last segment matches the pattern for numeric or X∆Y
#     if re.match(r'^\d+∆\d+$|^\d+$', last_segment):
#         return last_segment
#     return None

# # Apply the function to the HS_code column and update MFN_Rate only if a match is found
# data['MFN_Rate'] = data.apply(lambda row: extract_last_value(row['HS_code']) if extract_last_value(row['HS_code']) is not None else row['MFN_Rate'], axis=1)

In [105]:
# Convert HS_code column to string
data['HS_code'] = data['HS_code'].astype(str)

# Function to extract the last numeric value (including values like 6∆0)
def extract_last_value(value):
    # Split the row into segments based on whitespace
    segments = value.strip().split()
    # Get the last segment
    last_segment = segments[-1]
    # Check if the last segment matches the pattern for numeric or X∆Y
    if re.match(r'^\d+∆\d+$|^\d+$', last_segment):
        return last_segment
    return None

# Function to shift values to the right and insert the new value
def shift_and_insert(row):
    # Extract the last value from HS_code
    new_value = extract_last_value(row['HS_code'])
    if new_value:
        # Shift values to the right, starting from MFN_Rate
        row_values = row.tolist()
        # Find the index of MFN_Rate
        mfn_rate_index = row.index.get_loc('MFN_Rate')
        # Shift values to the right
        row_values[mfn_rate_index + 1:] = row_values[mfn_rate_index:-1]
        # Update MFN_Rate only if a match is found, otherwise keep the existing value
        row_values[mfn_rate_index] = new_value if new_value is not None else row_values[mfn_rate_index]
        # Update the row
        row = pd.Series(row_values, index=row.index)
    return row

# Apply the shift_and_insert function to each row
df = data.apply(shift_and_insert, axis=1)

In [106]:
# # Convert HS_code column to string
# data['HS_code'] = data['HS_code'].astype(str)

# # Function to extract the last numeric value
# def extract_last_value(value):
#     segments = value.strip().split()
#     last_segment = segments[-1]
#     if re.match(r'^\d+∆\d+$|^\d+$', last_segment):
#         return last_segment
#     return None

# # Function to check for decimal number pattern in HS_code
# def has_decimal_pattern(value):
#     return bool(re.search(r'\b\d+\.\d+\b', str(value)))

# # Function to process the DataFrame
# def shift_rows(data):
#     # Create a copy to avoid SettingWithCopyWarning
#     df = data.copy()
#     i = 0
#     while i < len(df):
#         row = df.iloc[i]
#         new_value = extract_last_value(row['HS_code'])
        
#         if new_value and not has_decimal_pattern(row['HS_code']):
#             # Shift current and subsequent rows until decimal pattern is found
#             j = i
#             while j < len(df):
#                 current_row = df.iloc[j]
#                 if has_decimal_pattern(current_row['HS_code']):
#                     break
                    
#                 row_values = current_row.tolist()
#                 mfn_rate_index = df.columns.get_loc('MFN_Rate')
                
#                 # Shift values to the right
#                 row_values[mfn_rate_index + 1:] = row_values[mfn_rate_index:-1]
                
#                 # For the first matching row, update MFN_Rate with new value
#                 if j == i:
#                     row_values[mfn_rate_index] = new_value
#                 else:
#                     # For subsequent rows, just shift existing values
#                     row_values[mfn_rate_index] = None
                
#                 # Update the row
#                 df.iloc[j] = row_values
#                 j += 1
            
#             # Skip the rows we've already processed
#             i = j
#         else:
#             i += 1
    
#     return df

# # Apply the transformation
# df = shift_rows(data)

In [107]:
df.head(50)

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,01.01 马、驴、骡:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-马:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.2100 --改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R ,韩 KR R R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0101.2900 --其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
8,nan,NaN,NaN,"冰IS,韩KR,澳AU,格GE,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-驴:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0101.3010 ---改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
18,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R 韩R , KR R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0101.3090 ---其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
23,nan,NaN,NaN,"冰IS,韩KR,澳 RAU, 格 GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0101.9000 -其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,惠LD,30,NaN,NaN,NaN
32,nan,NaN,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,nan,NaN,"R RAU R ,新西兰 NZ R ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,nan,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,nan,6,"韩R RKR ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,R,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,nan,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,nan,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,01.02 牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-家牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0102.2100 --改良种用 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0,惠LD,0,NaN,NaN,NaN
43,nan,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nan,NaN,"R RAS R 澳R , AU R 日R , JP R 韩R , KR R 新西兰R , NZ ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nan,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0102.2900 --其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,"惠LD,",30,NaN,NaN,NaN
48,nan,NaN,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,"柬KH,",NaN,NaN,NaN,NaN,NaN
49,nan,NaN,"R RAU R ,新西兰 NZ R ,柬KH,厄EC,马MV,港",NaN,NaN,"老LA,",NaN,NaN,NaN,NaN,NaN

In [108]:
# # Convert HS_code column to string
# data['HS_code'] = data['HS_code'].astype(str)

# # Function to extract the last numeric value (including values like 6∆0)
# def extract_last_value(value):
#     # Split the row into segments based on whitespace
#     segments = value.strip().split()
#     # Get the last segment
#     last_segment = segments[-1]
#     # Check if the last segment matches the pattern for numeric or X∆Y
#     if re.match(r'^\d+∆\d+$|^\d+$', last_segment):
#         return last_segment
#     return None

# # Function to shift values to the right and insert the new value
# def shift_and_insert(row):
#     # Skip shifting if new_col_2 is not empty
#     if pd.notna(row['new_col2']) and row['new_col2'] != '':
#         return row
    
#     # Extract the last value from HS_code
#     new_value = extract_last_value(row['HS_code'])
#     if new_value:
#         # Shift values to the right, starting from MFN_Rate
#         row_values = row.tolist()
#         # Find the index of MFN_Rate
#         mfn_rate_index = row.index.get_loc('MFN_Rate')
#         # Shift values to the right
#         row_values[mfn_rate_index + 1:] = row_values[mfn_rate_index:-1]
#         # Update MFN_Rate only if a match is found, otherwise keep the existing value
#         row_values[mfn_rate_index] = new_value if new_value is not None else row_values[mfn_rate_index]
#         # Update the row
#         row = pd.Series(row_values, index=row.index)
#     return row

# # Apply the shift_and_insert function to each row
# df = data.apply(shift_and_insert, axis=1)

In [109]:
#get me the rows where Unnamed: 7, Unnamed: 8 are not null as dataframe
df[df['new_col1'].notnull() & df['new_col2'].notnull()]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
12616,"2707.5000 -???????,??ISO 3405",3405,7,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,0,惠LD,30,NaN,NaN
12834,2711.1310 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12841,2711.1390 ---其他 5∆1,5∆1,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12847,2711.1400 --乙烯、丙烯、丁烯及丁二烯 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12855,2711.1910 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12863,2711.1990 ---其他 3,3,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12870,2711.2100 --天然气 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,NaN,0,惠LD,20,NaN,NaN
12875,2711.2900 --其他 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
26972,"4412.5919 ----其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
26978,"4412.5920 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26982,4412.5990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN
26988,4412.9100 --至少有一表层是热带木 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26994,"4412.9200 --其他,至少有一表层是非针叶木 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27001,4412.9920 ---中间至少有一层是本章本国注 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27005,"R4412.9930 ---其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
27011,"4412.9940 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27015,4412.9990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN

In [110]:
#replace 惠LD in new_col2 with 30
# df['new_col2'] = df['new_col2'].replace('惠LD', '30')

In [111]:
#get me the rows where Unnamed: 7, Unnamed: 8 are not null as dataframe
df[df['new_col1'].notnull() & df['new_col2'].notnull()]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
12616,"2707.5000 -???????,??ISO 3405",3405,7,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,0,惠LD,30,NaN,NaN
12834,2711.1310 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12841,2711.1390 ---其他 5∆1,5∆1,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12847,2711.1400 --乙烯、丙烯、丁烯及丁二烯 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12855,2711.1910 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12863,2711.1990 ---其他 3,3,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12870,2711.2100 --天然气 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,NaN,0,惠LD,20,NaN,NaN
12875,2711.2900 --其他 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
26972,"4412.5919 ----其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
26978,"4412.5920 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26982,4412.5990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN
26988,4412.9100 --至少有一表层是热带木 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26994,"4412.9200 --其他,至少有一表层是非针叶木 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27001,4412.9920 ---中间至少有一层是本章本国注 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27005,"R4412.9930 ---其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
27011,"4412.9940 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27015,4412.9990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN

In [112]:
df.head(50)

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,01.01 马、驴、骡:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-马:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.2100 --改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R ,韩 KR R R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0101.2900 --其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
8,nan,NaN,NaN,"冰IS,韩KR,澳AU,格GE,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-驴:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0101.3010 ---改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
18,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R 韩R , KR R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0101.3090 ---其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
23,nan,NaN,NaN,"冰IS,韩KR,澳 RAU, 格 GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0101.9000 -其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,惠LD,30,NaN,NaN,NaN
32,nan,NaN,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,nan,NaN,"R RAU R ,新西兰 NZ R ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,nan,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,nan,6,"韩R RKR ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,R,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,nan,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,nan,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,01.02 牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-家牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0102.2100 --改良种用 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0,惠LD,0,NaN,NaN,NaN
43,nan,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nan,NaN,"R RAS R 澳R , AU R 日R , JP R 韩R , KR R 新西兰R , NZ ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nan,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0102.2900 --其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,"惠LD,",30,NaN,NaN,NaN
48,nan,NaN,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,"柬KH,",NaN,NaN,NaN,NaN,NaN
49,nan,NaN,"R RAU R ,新西兰 NZ R ,柬KH,厄EC,马MV,港",NaN,NaN,"老LA,",NaN,NaN,NaN,NaN,NaN

In [113]:
# Function to check for Chinese characters
def contains_chinese(text):
    if pd.isna(text):
        return False
    return bool(re.search(r'[\u4e00-\u9fff]', str(text)))

# Load your data (replace with your actual file)
# data = pd.read_csv('your_file.csv')

# Find rows with Chinese characters in the specified column
chinese_rows = data[data['Preferential_Rate(Agreement rate)_1'].apply(contains_chinese)]

# Display the results
print(f"Found {len(chinese_rows)} rows with Chinese characters:")
print(chinese_rows)

# If you want to see just the specific column:
print("\nChinese text found in 'Preferential_Rate(Agreement rate)_1':")
print(chinese_rows['Preferential_Rate(Agreement rate)_1'].unique())

Found 44507 rows with Chinese characters:
                         HS_code MFN_Rate  \
31              0101.9000 -其他 10        0
32                           nan      NaN
33                           nan      NaN
35                           nan        2
36                           nan        6
...                          ...      ...
68138                        nan      NaN
68140  9705.2200 --灭绝或濒危物种及其部分 0        0
68141                        nan      NaN
68142                        nan      NaN
68143                        nan      NaN

                     Preferential_Rate(Agreement rate)_1  \
31                           东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,
32                      冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳
33                     R RAU R ,新西兰 NZ R ,柬KH,马MV,港HK,澳门
35                                                   巴PK
36                                           韩R RKR ,塞RS
...                                                  ...
68138                         柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门
68140                        东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,
68141                         瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟
68142  R RAS R 澳R , AU R ,日 R JP R ,韩 KR R R ,新西兰 NZ R ,
68143                         柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门

      Preferential_Rate(Agreement rate)  \
31                                  NaN
32                                  NaN
33                                  NaN
35                                  NaN
36                                  NaN
...                                 ...
68138                               NaN
68140                               NaN
68141                               NaN
68142                               NaN
68143                               NaN

      Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate)  \
31                                                     0
32                                                   NaN
33                                                   NaN
35                                                   NaN
36                                                   NaN
...                                                  ...
68138                                                NaN
68140                                                  0
68141                                                NaN
68142                                                NaN
68143                                                NaN

      General_Tariff_Rate Return_to_General new_col1  new_col2  guard_col1  \
31                    惠LD                30      NaN       NaN         NaN
32                    NaN               NaN      NaN       NaN         NaN
33                    NaN               NaN      NaN       NaN         NaN
35                    NaN               NaN      NaN       NaN         NaN
36                    NaN               NaN      NaN       NaN         NaN
...                   ...               ...      ...       ...         ...
68138                 NaN               NaN      NaN       NaN         NaN
68140                 惠LD                 0      NaN       NaN         NaN
68141                 NaN               NaN      NaN       NaN         NaN
68142                 NaN               NaN      NaN       NaN         NaN
68143                 NaN               NaN      NaN       NaN         NaN

       guard_col2
31            NaN
32            NaN
33            NaN
35            NaN
36            NaN
...           ...
68138         NaN
68140         NaN
68141         NaN
68142         NaN
68143         NaN

[44507 rows x 11 columns]

Chinese text found in 'Preferential_Rate(Agreement rate)_1':
['东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,' '冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳'
 'R RAU R ,新西兰 NZ R ,柬KH,马MV,港HK,澳门' ...
 '韩R RKR R ,新西兰 NZ R ,柬KH,马MV,港HK,澳'
 'KR,澳 RAU, 格 GE, 毛 MU, 东盟R AS R ,澳 AU R ,'
 '日R RJP R 韩R , KR R 新西兰R , NZ ,柬KH,马MV,港']

In [114]:
# Function to check if a value contains Chinese characters
def contains_chinese(value):
    if pd.isna(value) or value is None:
        return False  # Ignore null values
    # Regex to match Chinese characters
    return bool(re.search(r'[\u4e00-\u9fff]', value))

# Function to shift row values to the right if Chinese characters are found
def shift_row(row):
    # Check if the value in Preferential_Rate(Agreement rate)_1 contains Chinese characters
    if contains_chinese(row['Preferential_Rate(Agreement rate)_1']):
        # Get the index of Preferential_Rate(Agreement rate)_1
        start_index = row.index.get_loc('Preferential_Rate(Agreement rate)_1')
        # Shift values to the right
        row_values = row.tolist()
        row_values[start_index + 1:] = row_values[start_index:-1]
        # Add null to Preferential_Rate(Agreement rate)_1
        row_values[start_index] = None
        # Update the row
        row = pd.Series(row_values, index=row.index)
    return row

# Apply the shift_row function to each row
df2 = df.apply(shift_row, axis=1)

In [115]:
#get me the rows where Unnamed: 7, Unnamed: 8 are not null as dataframe
df2[df2['new_col1'].notnull() & df2['new_col2'].notnull()]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
12616,"2707.5000 -???????,??ISO 3405",3405,7,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,0,惠LD,30,NaN,NaN
12834,2711.1310 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12841,2711.1390 ---其他 5∆1,5∆1,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12847,2711.1400 --乙烯、丙烯、丁烯及丁二烯 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12855,2711.1910 ---直接灌注香烟打火机及类似打 5,5,0,"东盟AS,智CL,新西兰NZ,新加坡SG,秘PE,哥",NaN,NaN,0,惠LD,80,NaN,NaN
12863,2711.1990 ---其他 3,3,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
12870,2711.2100 --天然气 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,NaN,0,惠LD,20,NaN,NaN
12875,2711.2900 --其他 5,5,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,0,惠LD,20,NaN,NaN
26972,"4412.5919 ----其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
26978,"4412.5920 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26982,4412.5990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN
26988,4412.9100 --至少有一表层是热带木 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
26994,"4412.9200 --其他,至少有一表层是非针叶木 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27001,4412.9920 ---中间至少有一层是本章本国注 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27005,"R4412.9930 ---其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
27011,"4412.9940 ---其他,中间至少含有一层木碎 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
27015,4412.9990 ---其他 4∆0,4∆0,0,"东盟AS,智CL,巴PK,新西兰NZ,新加坡SG,秘",NaN,NaN,NaN,0,惠LD,30.0,NaN

In [116]:
# Function to check for Chinese characters
def contains_chinese(text):
    if pd.isna(text):
        return False
    return bool(re.search(r'[\u4e00-\u9fff]', str(text)))

# Load your data (replace with your actual file)
# data = pd.read_csv('your_file.csv')

# Find rows with Chinese characters in the specified column
chinese_rows = df2[df2['Preferential_Rate(Agreement rate)_1'].apply(contains_chinese)]

# Display the results
print(f"Found {len(chinese_rows)} rows with Chinese characters:")
print(chinese_rows)

# If you want to see just the specific column:
print("\nChinese text found in 'Preferential_Rate(Agreement rate)_1':")
print(chinese_rows['Preferential_Rate(Agreement rate)_1'].unique())

Found 0 rows with Chinese characters:
Empty DataFrame
Columns: [HS_code, MFN_Rate, Preferential_Rate(Agreement rate)_1, Preferential_Rate(Agreement rate), Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate), General_Tariff_Rate, Return_to_General, new_col1, new_col2, guard_col1, guard_col2]
Index: []

Chinese text found in 'Preferential_Rate(Agreement rate)_1':
[]

In [117]:
# extract where HScode contains value like 4412.5919 and the next 5 lines. Use regex. To ensure no missing data points. 
# Convert HS_code column to string
df2['HS_code'] = df2['HS_code'].astype(str)

# Find all indices where HS_code contains '4412.5919' using regex
pattern = r'4412\.9100'
matching_indices = data[data['HS_code'].str.contains(pattern, regex=True)].index.tolist()

# For each matching index, get the next 5 rows (including the matching row)
result_indices = []
for idx in matching_indices:
    end_idx = min(idx + 6, len(df2))  # Ensure we don't go beyond DataFrame length
    result_indices.extend(range(idx, end_idx))

# Remove duplicates and sort the indices
result_indices = sorted(list(set(result_indices)))

# Extract the resulting rows
result_df = df2.iloc[result_indices].reset_index(drop=True)

# Display the result
result_df

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,4412.9100 --至少有一表层是热带木 6∆0,6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,柬KH,塞RS,",NaN,NaN,NaN,0,惠LD,30.0,NaN
1,nan,NaN,None,"港HK,澳门MO",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nan,2,None,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,nan,2.6,None,韩KR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,3.6,None,"尼NI,厄EC",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,5,None,东盟AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
# def process_data(data):
#     # Make a copy of the original data to avoid modifying it directly
#     df = data.copy()
    
#     # Iterate through each row
#     for index, row in df.iterrows():
#         # Check conditions: MFN_Rate has value AND HS_code is empty/null
#         #remove white space from HS_code
#         row['HS_code'] = row['HS_code'].strip()
#         if pd.notna(row['MFN_Rate']) and (pd.isna(row['HS_code']) or row['HS_code'] == 'nan'or row['HS_code'] == 'R'):
            
#             # Store the original MFN_Rate value
#             mfn_value = row['MFN_Rate']
            
#             # Move MFN_Rate value to Preferential_Rate(Agreement rate)_1
#             df.at[index, 'Preferential_Rate(Agreement rate)_1'] = mfn_value
            
#             # Set MFN_Rate to null
#             df.at[index, 'MFN_Rate'] = np.nan
    
#     return df

# # Apply the transformation
# processed_data = process_data(df2)

In [119]:
def process_data(data):
    # Make a copy of the original data
    df = data.copy()
    
    # Iterate through each row
    for index, row in df.iterrows():
        # Remove whitespace from HS_code
        hs_code = str(row['HS_code']).strip()
        
        # Check if HS_code doesn't contain a decimal number pattern
        if not re.search(r'\d+\.\d+', hs_code):
            # Store the original MFN_Rate value if it exists
            if pd.notna(row['MFN_Rate']):
                mfn_value = row['MFN_Rate']
                
                # Shift values to the right
                # Move MFN_Rate to Preferential_Rate(Agreement rate)_1
                df2.at[index, 'Preferential_Rate(Agreement rate)_1'] = mfn_value
                
                # Set MFN_Rate to null
                df2.at[index, 'MFN_Rate'] = np.nan
    
    return df2

# Apply the transformation
processed_data = process_data(df2)

In [120]:
# extract where HScode contains value like 4412.5919 and the next 5 lines. Use regex. To ensure no missing data points. 
# Convert HS_code column to string
processed_data['HS_code'] = processed_data['HS_code'].astype(str)

# Find all indices where HS_code contains '4412.5919' using regex
pattern = r'4412\.5919'
matching_indices = data[data['HS_code'].str.contains(pattern, regex=True)].index.tolist()

# For each matching index, get the next 5 rows (including the matching row)
result_indices = []
for idx in matching_indices:
    end_idx = min(idx + 6, len(processed_data))  # Ensure we don't go beyond DataFrame length
    result_indices.extend(range(idx, end_idx))

# Remove duplicates and sort the indices
result_indices = sorted(list(set(result_indices)))

# Extract the resulting rows
result_df = processed_data.iloc[result_indices].reset_index(drop=True)

# Display the result
result_df

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,"4412.5919 ----其他,中间至少有一层是其他 6∆0",6∆0,0,"智CL,新西兰NZ,瑞CH,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,0,惠LD,30.0,NaN
1,热带木 R,NaN,None,"R AU R ,韩 KR R ,新西兰R RNZ ,柬KH,塞RS,港",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nan,NaN,None,"HK,澳门MO",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,2.1,韩KR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,2.5,日R RJP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,3.6,"尼NI,厄EC",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
processed_data.head(50)

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,01.01 马、驴、骡:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-马:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.2100 --改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R ,韩 KR R R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0101.2900 --其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
8,nan,NaN,NaN,"冰IS,韩KR,澳AU,格GE,毛MU,东盟R RAS ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-驴:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0101.3010 ---改良种用,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0 惠LD 0,NaN,NaN,NaN,NaN,NaN
18,nan,NaN,NaN,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,NaN,NaN,"R RAS R 澳R , AU ,日R RJP R 韩R , KR R ,新西兰 NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,nan,NaN,NaN,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0101.3090 ---其他,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0 惠LD 30,NaN,NaN,NaN,NaN,NaN
23,nan,NaN,NaN,"冰IS,韩KR,澳 RAU, 格 GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,nan,NaN,NaN,"R RAU ,新西兰R RNZ ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,R,NaN,6,"韩 KR R ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0101.9000 -其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,惠LD,30,NaN,NaN,NaN
32,nan,NaN,None,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,nan,NaN,None,"R RAU R ,新西兰 NZ R ,柬KH,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,nan,NaN,2,巴PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,nan,NaN,6,"韩R RKR ,塞RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,R,NaN,6.4,日R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,nan,NaN,8,尼NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,nan,NaN,9,厄EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,01.02 牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-家牛:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0102.2100 --改良种用 0,0,0,"东盟AS,智CL,巴PK,新西兰NZ,秘PE,哥CR,",NaN,0,惠LD,0,NaN,NaN,NaN
43,nan,NaN,None,"瑞CH,冰IS,韩KR,澳AU,格GE,毛MU,东盟",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nan,NaN,None,"R RAS R 澳R , AU R 日R , JP R 韩R , KR R 新西兰R , NZ ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nan,NaN,None,"柬KH,尼NI,厄EC,塞RS,马MV,港HK,澳门",NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,nan,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0102.2900 --其他 10,10,0,"东盟AS,智CL,新西兰NZ,秘PE,哥CR,瑞CH,",NaN,0,"惠LD,",30,NaN,NaN,NaN
48,nan,NaN,None,"冰 RIS,韩KR,澳AU,格GE,毛MU,东盟 AS R ,澳",NaN,NaN,"柬KH,",NaN,NaN,NaN,NaN
49,nan,NaN,None,"R RAU R ,新西兰 NZ R ,柬KH,厄EC,马MV,港",NaN,NaN,"老LA,",NaN,NaN,NaN,NaN

In [122]:
#shift columns to the right with MO in Preferential_Rate_1
# Function to process Preferential_Rate columns
def process_preferential_rates(data):
    
    # Iterate through each row
    for index, row in df.iterrows():
        pref_rate_1 = row['Preferential_Rate(Agreement rate)_1']
        
        # Check if Preferential_Rate_1 contains "MO" (case insensitive)
        if pd.notna(pref_rate_1) and re.search(r'MO', str(pref_rate_1), re.IGNORECASE):
            
            # Store the original Preferential_Rate_1 value
            original_value = pref_rate_1
            
            # Move the value to Preferential_Rate
            df2.at[index, 'Preferential_Rate(Agreement rate)'] = original_value
            
            # Set Preferential_Rate_1 to null
            df2.at[index, 'Preferential_Rate(Agreement rate)_1'] = np.nan
    
    return df2

# Apply the transformation
df2 = process_preferential_rates(df2)

In [123]:
def remove_chinese_chars(text):
    """Remove Chinese characters from text using regex"""
    if pd.isna(text):
        return text
    return re.sub(r'[\u4e00-\u9fff\u3400-\u4dbf\U00020000-\U0002a6df\U0002a700-\U0002b73f\U0002b740-\U0002b81f\U0002b820-\U0002ceaf]+', '', str(text))

# Columns to process
columns_to_clean = [
    'HS_code', 'MFN_Rate', 'Preferential_Rate(Agreement rate)_1',
    'Preferential_Rate(Agreement rate)',
    'Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate)',
    'General_Tariff_Rate', 'Return_to_General', 'new_col1', 'new_col2',
    'guard_col'
]

# Apply the cleaning function to each specified column
for col in columns_to_clean:
    if col in data.columns:
        df2[col] = df2[col].apply(remove_chinese_chars)

# Optional: Verify the cleaning
print("Sample after cleaning:")

Sample after cleaning:

In [124]:
df2.head(50)

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,01.01 、、:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.2100 --,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0 LD 0,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,NaN,"R RAS R R , AU ,R RJP R , KR R R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0101.2900 --,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0 LD 30,NaN,NaN,NaN,NaN,NaN
8,nan,NaN,NaN,"IS,KR,AU,GE,MU,R RAS ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nan,NaN,NaN,"R RAU ,R RNZ ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0101.3010 ---,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0 LD 0,NaN,NaN,NaN,NaN,NaN
18,nan,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,NaN,NaN,"R RAS R R , AU ,R RJP R R , KR R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,nan,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0101.3090 ---,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0 LD 30,NaN,NaN,NaN,NaN,NaN
23,nan,NaN,NaN,"IS,KR, RAU, GE,MU, AS R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,nan,NaN,NaN,"R RAU ,R RNZ ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0101.9000 - 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,LD,30,NaN,NaN,NaN
32,nan,NaN,None,"RIS,KR,AU,GE,MU, AS R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,nan,NaN,None,"R RAU R , NZ R ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,nan,NaN,6,"R RKR ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,01.02 :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0102.2100 -- 0,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0,LD,0,NaN,NaN,NaN
43,nan,NaN,None,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nan,NaN,None,"R RAS R R , AU R R , JP R R , KR R R , NZ ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nan,NaN,None,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0102.2900 -- 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,"LD,",30,NaN,NaN,NaN
48,nan,NaN,None,"RIS,KR,AU,GE,MU, AS R ,",NaN,NaN,"KH,",NaN,NaN,NaN,NaN
49,nan,NaN,None,"R RAU R , NZ R ,KH,EC,MV,",NaN,NaN,"LA,",NaN,NaN,NaN,NaN

In [125]:
# df2.to_csv('review_data.csv', index=False)

In [126]:
df2.iloc[50:100]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
50,nan,NaN,NaN,"HK,MO",NaN,NaN,MM,NaN,NaN,NaN,NaN
51,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,0102.3100 -- 0,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0,LD,0,NaN,NaN,NaN
57,nan,NaN,None,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,nan,NaN,None,"R RAS R R , AU R R , JP R , KR R R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,nan,NaN,None,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,0102.3900 -- 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,"LD,",30,NaN,NaN,NaN
62,nan,NaN,None,"RIS,KR,AU,GE,MU, AS R ,",NaN,NaN,"KH,",NaN,NaN,NaN,NaN
63,nan,NaN,None,"R RAU R , NZ R ,KH,EC,MV,",NaN,NaN,"LA,",NaN,NaN,NaN,NaN
64,nan,NaN,NaN,"HK,MO",NaN,NaN,MM,NaN,NaN,NaN,NaN
65,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,R,NaN,6,"R KR ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,0102.9010 --- 0,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0,LD,0,NaN,NaN,NaN
71,nan,NaN,None,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,nan,NaN,None,"R RAS R , AU R R , R JP R , KR R R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,nan,NaN,None,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,0102.9090 --- 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,"LD,",30,NaN,NaN,NaN
76,nan,NaN,None,"IS, RKR,AU,GE,MU, AS R ,",NaN,NaN,"KH,",NaN,NaN,NaN,NaN
77,nan,NaN,None,"R RAU ,R RNZ ,KH,MV,HK,",NaN,NaN,"LA,",NaN,NaN,NaN,NaN
78,nan,NaN,NaN,MO,NaN,MM,NaN,NaN,NaN,NaN,NaN
79,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,R,NaN,6,"R KR ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,nan,NaN,6.4,R RJP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,01.03 :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,0103.1000 - 0,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0,LD,0,NaN,NaN,NaN
86,nan,NaN,None,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,nan,NaN,None,"R RAS R , AU R ,R RJP ,R RKR R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,nan,NaN,None,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,--50:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,0103.9110 ---10 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,"LD,",50,NaN,NaN,NaN
93,nan,NaN,None,"IS,KR,AU,GE,MU,R RAS ,",NaN,NaN,"KH,",NaN,NaN,NaN,NaN
94,nan,NaN,None,"R RAU R R , NZ ,KH,MV,HK,",NaN,NaN,MM,NaN,NaN,NaN,NaN
95,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
df2.head(50)

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate)_1,Preferential_Rate(Agreement rate),Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate),General_Tariff_Rate,Return_to_General,new_col1,new_col2,guard_col1,guard_col2
0,01.01 、、:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.2100 --,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0 LD 0,NaN,NaN,NaN,NaN,NaN
3,nan,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nan,NaN,NaN,"R RAS R R , AU ,R RJP R , KR R R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,nan,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0101.2900 --,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0 LD 30,NaN,NaN,NaN,NaN,NaN
8,nan,NaN,NaN,"IS,KR,AU,GE,MU,R RAS ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nan,NaN,NaN,"R RAU ,R RNZ ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0101.3010 ---,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0 LD 0,NaN,NaN,NaN,NaN,NaN
18,nan,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,NaN,NaN,"R RAS R R , AU ,R RJP R R , KR R , NZ R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,nan,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0101.3090 ---,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0 LD 30,NaN,NaN,NaN,NaN,NaN
23,nan,NaN,NaN,"IS,KR, RAU, GE,MU, AS R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,nan,NaN,NaN,"R RAU ,R RNZ ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,R,NaN,6,"KR R ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0101.9000 - 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,LD,30,NaN,NaN,NaN
32,nan,NaN,None,"RIS,KR,AU,GE,MU, AS R ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,nan,NaN,None,"R RAU R , NZ R ,KH,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,nan,NaN,2,PK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,nan,NaN,6,"R RKR ,RS",NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,R,NaN,6.4,R JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,nan,NaN,8,NI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,nan,NaN,9,EC,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,01.02 :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,-:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0102.2100 -- 0,0,0,"AS,CL,PK,NZ,PE,CR,",NaN,0,LD,0,NaN,NaN,NaN
43,nan,NaN,None,"CH,IS,KR,AU,GE,MU,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nan,NaN,None,"R RAS R R , AU R R , JP R R , KR R R , NZ ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nan,NaN,None,"KH,NI,EC,RS,MV,HK,",NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,nan,NaN,NaN,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0102.2900 -- 10,10,0,"AS,CL,NZ,PE,CR,CH,",NaN,0,"LD,",30,NaN,NaN,NaN
48,nan,NaN,None,"RIS,KR,AU,GE,MU, AS R ,",NaN,NaN,"KH,",NaN,NaN,NaN,NaN
49,nan,NaN,None,"R RAU R , NZ R ,KH,EC,MV,",NaN,NaN,"LA,",NaN,NaN,NaN,NaN

In [128]:
# df2.to_csv('review_data3.csv', index=False)

In [129]:
df2.columns

Index(['HS_code', 'MFN_Rate', 'Preferential_Rate(Agreement rate)_1',
       'Preferential_Rate(Agreement rate)',
       'Preferential_Tariff_Rate(Special_Preferential_Tariff_Rate)',
       'General_Tariff_Rate', 'Return_to_General', 'new_col1', 'new_col2',
       'guard_col1', 'guard_col2'],
      dtype='object')

In [130]:
# def remove_standalone_R(df):
#     """
#     Remove all standalone 'R' characters from all columns in the DataFrame using regex.
#     Handles cases where 'R' is:
#     - At start of string (Rvalue)
#     - At end of string (valueR)
#     - Surrounded by spaces (value R value)
#     - Punctuation cases (value,R,value or value.R.value)
#     """
    
#     # Regex pattern to match standalone R (case-sensitive)
#     pattern = r'(?:^|\s)R(?:\s|$)|(?:^|\s)R(\W)|(\W)R(?:\s|$)'
    
#     # Iterate through all columns
#     for col in df2.columns:
#         # Apply regex substitution
#         df2[col] = df2[col].apply(
#             lambda x: re.sub(pattern, 
#                            lambda m: m.group(1) if m.group(1)
#                            else (m.group(2) if m.group(2) 
#                            else ' '), 
#                            str(x))
#         )
#         # Clean up any double spaces created
#         df2[col] = df2[col].str.replace(r'\s+', ' ').str.strip()
#         # Convert empty strings to NaN
#         df2[col] = df2[col].replace({'': np.nan})
    
#     return df2

# # Apply the cleaning function to your DataFrame
# df2 = remove_standalone_R(df2)

In [131]:
def shift_rows_left(data):
    """
    When both Preferential_Rate columns contain numbers, shift other columns left (except HS_code)
    """
    df = data.copy()
    
    # Columns to check for numbers
    pref_cols = [
        'Preferential_Rate(Agreement rate)_1',
        'Preferential_Rate(Agreement rate)'
    ]
    
    # Columns that can be shifted (all except HS_code)
    shift_cols = [col for col in df.columns if col != 'HS_code']
    
    for index, row in df.iterrows():
        # Check if both preferential columns contain numbers
        both_numeric = all(
            pd.notna(row[col]) and 
            re.match(r'^[+-]?\d*\.?\d+$', str(row[col]))
            for col in pref_cols
        )
        
        if both_numeric:
            # Get values from shiftable columns
            values = row[shift_cols].tolist()
            
            # Shift left by one position (first value gets dropped)
            shifted_values = values[1:] + [np.nan]
            
            # Update the row (except HS_code)
            for i, col in enumerate(shift_cols):
                df.at[index, col] = shifted_values[i]
    
    return df

# Apply the transformation
df2 = shift_rows_left(df2)

In [132]:
df2.to_csv('review_data7.csv', index=False)

### Used TEXTJOIN on excel to join tarrifs(last 4 roles) before proceeding with this.

In [133]:
clean_V1 = pd.read_csv('clean_V1.csv')

# Assuming clean_V1 is your DataFrame
# Create three new columns initialized with NaN
clean_V1['column1'] = np.nan
clean_V1['column2'] = np.nan
clean_V1['column3'] = np.nan

# Iterate through each row
for index, row in clean_V1.iterrows():
    values = str(row['all']).split()  # Split by space
    
    if len(values) == 3:
        # Case with 3 values
        clean_V1.at[index, 'column1'] = values[0]
        clean_V1.at[index, 'column2'] = values[1]
        clean_V1.at[index, 'column3'] = values[2]
    elif len(values) == 1:
        # Case with single value
        clean_V1.at[index, 'column2'] = values[0]
    # Cases with 0 or 2 values will leave all columns as NaN

# Optional: Drop the original 'all' column if no longer needed
# clean_V1 = clean_V1.drop('all', axis=1)

clean_V1.head(50)

C:\Users\User\AppData\Local\Temp\ipykernel_10364\1139954647.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  clean_V1.at[index, 'column2'] = values[0]
C:\Users\User\AppData\Local\Temp\ipykernel_10364\1139954647.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  clean_V1.at[index, 'column1'] = values[0]
C:\Users\User\AppData\Local\Temp\ipykernel_10364\1139954647.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  clean_V1.at[index, 'column3'] = values[2]

,HS_code,MFN_Rate,Preferential_Rate(Agreement rate_1,Preferential_Rate(Agreement rate,all,column1,column2,column3
0,1.01,NaN,NaN,NaN,NaN,NaN,nan,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN
2,101.21,0,0,"AS,CL,PK,NZ,PE,CR,",0 LD 0,0,LD,0
3,NaN,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,nan,NaN
4,NaN,NaN,NaN,"RAS R , AU ,RJP , KR R , NZ ,",NaN,NaN,nan,NaN
5,NaN,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,nan,NaN
6,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
7,101.29,10,0,"AS,CL,NZ,PE,CR,CH,",0 LD 30,0,LD,30
8,NaN,NaN,NaN,"IS,KR,AU,GE,MU,RAS ,",NaN,NaN,nan,NaN
9,NaN,NaN,NaN,"RAU ,RNZ ,KH,MV,HK,",NaN,NaN,nan,NaN
10,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
11,NaN,NaN,2,PK,NaN,NaN,nan,NaN
12,NaN,NaN,6,"KR ,RS",NaN,NaN,nan,NaN
13,NaN,NaN,6.4,JP,NaN,NaN,nan,NaN
14,NaN,NaN,8,NI,NaN,NaN,nan,NaN
15,NaN,NaN,9,EC,NaN,NaN,nan,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN
17,0101.3010 -,0,0,"AS,CL,PK,NZ,PE,CR,",0 LD 0,0,LD,0
18,NaN,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,nan,NaN
19,NaN,NaN,NaN,"RAS R , AU ,RJP R , KR , NZ ,",NaN,NaN,nan,NaN
20,NaN,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,nan,NaN
21,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
22,0101.3090 -,10,0,"AS,CL,NZ,PE,CR,CH,",0 LD 30,0,LD,30
23,NaN,NaN,NaN,"IS,KR, RAU, GE,MU, AS ,",NaN,NaN,nan,NaN
24,NaN,NaN,NaN,"RAU ,RNZ ,KH,MV,HK,",NaN,NaN,nan,NaN
25,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
26,NaN,NaN,2,PK,NaN,NaN,nan,NaN
27,NaN,NaN,6,"KR ,RS",NaN,NaN,nan,NaN
28,NaN,NaN,6.4,JP,NaN,NaN,nan,NaN
29,NaN,NaN,8,NI,NaN,NaN,nan,NaN
30,NaN,NaN,9,EC,NaN,NaN,nan,NaN
31,0101.9000 - 10,10,0,"AS,CL,NZ,PE,CR,CH,",0 LD 30,0,LD,30
32,NaN,NaN,NaN,"RIS,KR,AU,GE,MU, AS ,",NaN,NaN,nan,NaN
33,NaN,NaN,NaN,"RAU , NZ ,KH,MV,HK,",NaN,NaN,nan,NaN
34,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
35,NaN,NaN,2,PK,NaN,NaN,nan,NaN
36,NaN,NaN,6,"RKR ,RS",NaN,NaN,nan,NaN
37,NaN,NaN,6.4,JP,NaN,NaN,nan,NaN
38,NaN,NaN,8,NI,NaN,NaN,nan,NaN
39,NaN,NaN,9,EC,NaN,NaN,nan,NaN
40,1.02,NaN,NaN,NaN,NaN,NaN,nan,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN
42,0102.2100 0,0,0,"AS,CL,PK,NZ,PE,CR,",0 LD 0,0,LD,0
43,NaN,NaN,NaN,"CH,IS,KR,AU,GE,MU,",NaN,NaN,nan,NaN
44,NaN,NaN,NaN,"RAS R , AU R , JP R , KR R , NZ ,",NaN,NaN,nan,NaN
45,NaN,NaN,NaN,"KH,NI,EC,RS,MV,HK,",NaN,NaN,nan,NaN
46,NaN,NaN,NaN,MO,NaN,NaN,nan,NaN
47,0102.2900 10,10,0,"AS,CL,NZ,PE,CR,CH,","0 LD, 30",0,"LD,",30
48,NaN,NaN,NaN,"RIS,KR,AU,GE,MU, AS ,","KH,",NaN,"KH,",NaN
49,NaN,NaN,NaN,"RAU , NZ ,KH,EC,MV,","LA,",NaN,"LA,",NaN

In [134]:
clean_V1.to_csv('clean_V2.csv', index=False)

In [136]:
# Process 'hs_code' column
clean_V1['HS_CODE'] = clean_V1['HS_code'].astype(str).str.split().str[0]

In [135]:
clean_V1.columns

Index(['HS_code', 'MFN_Rate', 'Preferential_Rate(Agreement rate_1',
       'Preferential_Rate(Agreement rate', 'all', 'column1', 'column2',
       'column3'],
      dtype='object')

In [137]:
clean_V1.to_csv('clean_V3.csv', index=False)

In [140]:
# Process the HS code column - vectorized approach (recommended)
clean_V1['HS_CODE2'] = clean_V1['HS_code'].astype(str).str.split().str[0].apply(
    lambda x: f'"{x}"' if pd.notna(x) and x != 'nan' else x)

In [141]:
clean_V1.to_csv('clean_V4.csv', index=False)